title: Phuong Tseng
logo: "/images/phuong.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Professional data, mapping, and research analyst with more than 5 years of experience researching, 
  mapping, analyzing, and visualizing racial, social, environmental health, and socioeconomic 
  inequities using R, SQL, ArcGIS, QGIS, and other toolkits. I have experiences working with federal, 
  county, and local government databases. 
  <br><br>
  In adition to these open data portals, I have also worked with various proprietary housing development, 
  health, and finance data at the international, national, to household-level.
  <br><br>
  <br><br>
  <br><br>
  <br><br>
  <a href="https://www.linkedin.com/in/phuongntseng/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
